name: ZS Docker PostGIS CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:

  make-docker-images:
    strategy:
      matrix:
        postgres: [12, 13, 14, 15, 16]
        postgis: ['3.4']
        variant: [default, alpine]
        include:
          - postgres: 15
            postgis: master
            variant: default
          - postgres: 16
            postgis: master
            variant: default
          - postgres: 11
            postgis: 3.3
            variant: default
          - postgres: 11
            postgis: 3.3
            variant: alpine

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64,amd64'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
      run: make test
      env:
        REPO_NAME: ${{ env.REGISTRY }}
        IMAGE_NAME: zerosubnet/postgis

    - name: Login to dockerhub
      uses: docker/login-action@v2
      if: ${{  (github.ref == 'refs/heads/zs') && (github.event_name != 'pull_request')  }}
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push docker image to dockerhub
      if: ${{  (github.ref == 'refs/heads/zs') && (github.event_name != 'pull_request')  }}
      env:
        REPO_NAME: ${{ env.REGISTRY }}
        IMAGE_NAME: zerosubnet/postgis
      run: make push

